apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: advocatr
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/advocatr-app-dev/advocatr
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgresql://advocatr-user:AdvocatrUser2024%21@35.230.134.172:5432/advocatr"
            - name: SESSION_SECRET
              value: "a1b2c3d4e5f6789012345678901234567890abcdef1234567890abcdef12345678" 